Basic:
  # 抓包获得 "xxxxxxxxxx"
  device_id: ""
  # 抓包获得 "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxx"
  authorization: ""

  # api延迟 默认0.5秒 防止被封，虽然兽耳官方并不管
  delay: 0.5
  debug: False
# 脚本功能相关设置
Task:
  Sign:
    # 任务：每日签到
    # 是否启用
    enable: True
  EnergyExchange:
    # 任务：能量值兑换成长值。随时间增加的那个，不是电力能源
    enable: True
    # 要换给哪个助手 "character_code"
    character_code: "character_miruku2"
  EnergyCenter:
    # 任务：能源中心:硬币换电力
    enable: True
  OrdinaryWork:
    # 任务：公会悬赏:电力换硬币
    enable: True
    # 要接取任务的助手
    work_characters: ["character_ruri", "character_nemuri"]
  Task:
    # 任务：助手每日任务:完成可获得好感度
    enable: True
    # 要接取助手任务的助手
    task_characters: ["character_momona", "character_miruku2"]
  MailReceive:
    # 任务：邮件领取:一键领取邮件奖励
    enable: True
  CoinMall:
    # 任务：硬币商店:换取每周刷新
    enable: True
    exchange_list: ['_supplementary_signature_card','_work_refresh_ticket','energy_speedup_ticket']